AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
  NewCops: enable

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false
